
---
title: "Create summary statistics for selected variables"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
```

* * *
```{r}
# Download merged data
merged_df <- read.table('Datasets/merged/raw_dataset.csv', sep = ',', header = TRUE)
head(merged_df)
```

```{r}
# Subset for only variables we are interested in
var_list = c('VEH', 'MV', 'NP', 'RMSP', 'ENG',
             'MARHT','SCHL', 'RACNUM', 'AGEP', 'WKL', 'PINCP')
df <- merged_df[,var_list]
head(df)
```

```{r}
# Convert type, binning on variables

# VEH: Vehicles
df$VEH <- factor(df$VEH, ordered = TRUE, levels = c(0,1,2,3,4,5,6), 
                 labels = c(1,2,3,4,5,6,7))

# MV: When move into house
df$MV <- factor(df$MV, ordered = TRUE, levels = c(1,2,3,4,5,6,7))

# NP: Number of persons in this household
# Merge 7-20
df$NP[df$NP>=7] <- 7
df$NP <- factor(df$NP, ordered = TRUE, levels = 1:7)

# RMSP: Number of rooms
# 1-19 maximum
df$RMSP <- factor(df$RMSP, ordered = TRUE, levels = min(df$RMSP):max(df$RMSP))

# ENG: Ability to speak english 
# Turn NA into one separate group: Excellent
df$ENG[is.na(df$ENG)] <- 0
# reorder
df$ENG <- 5 - df$ENG
df$ENG <- factor(df$ENG, ordered = TRUE, levels = 1:5)

# MARHT: Number of times married - start at 1
df$MARHT[is.na(df$MARHT)] <- 0
df$MARHT <- factor(df$MARHT, ordered = TRUE, levels = c(0,1,2,3),
                   labels = c(1,2,3,4))

# SCHL: Educational attainment
# Group together no diploma group
df$SCHL[df$SCHL <=15 & df$SCHL>=2]  <- 2
# Group together high school group
df$SCHL[df$SCHL <=19 & df$SCHL>=16]  <- 3
# Group together master degree group
df$SCHL[df$SCHL <=23 & df$SCHL>=22]  <- 22
df$SCHL <- factor(df$SCHL, ordered = TRUE, levels = c(1,2,3,20,21,22,24),
                  labels = c(1,2,3,4,5,6,7))

# RACNUM: Number of major race groups represented
# Combine level 2 to 6
df$RACNUM[df$RACNUM>=2] <- 2
df$RACNUM <- factor(df$RACNUM, ordered = TRUE, levels = 1:2)

# AGEP: Age
# Bin age by 5 years
df$AGEP <- cut(df$AGEP, seq(15,100,5), 
                 right=FALSE,
                 labels = 1:17)
df$AGEP <- factor(df$AGEP, ordered = TRUE, levels = 1:17)

# WKL: When last worked
# group N/A as class 3 (never worked)
df$WKL[is.na(df$WKL)] <- 3
# reorder
df$WKL <- 4 - df$WKL
df$WKL <- factor(df$WKL, ordered = TRUE, levels = 1:3)

# PINCP: Total person's income
# reassign labels (the minimum is over -19998), binusing 20k range
df$PINCP[df$PINCP > 0 & df$PINCP <= 20000] <- 3
df$PINCP[df$PINCP > 20000 & df$PINCP <= 40000] <- 4
df$PINCP[df$PINCP > 40000 & df$PINCP <= 60000] <- 5
df$PINCP[df$PINCP > 60000 & df$PINCP <= 80000] <- 6
df$PINCP[df$PINCP > 80000 & df$PINCP <= 100000] <- 7
df$PINCP[df$PINCP > 100000 & df$PINCP <= 120000] <- 8
df$PINCP[df$PINCP > 120000 & df$PINCP <= 140000] <- 9
df$PINCP[df$PINCP > 140000 & df$PINCP <= 160000] <- 10
df$PINCP[df$PINCP > 160000 & df$PINCP <= 180000] <- 11
df$PINCP[df$PINCP > 180000 & df$PINCP <= 200000] <- 12
df$PINCP[df$PINCP > 200000] <- 13
df$PINCP[df$PINCP == 0] <- 2
df$PINCP[df$PINCP < 0] <- 1
df$PINCP <- factor(df$PINCP, ordered = TRUE, levels = 1:13)
```

```{r}
# Save data as r object
save(df, file = "ordinalPUMS.Rdata")
```

Distribution and number of records:

```{r}
summary(df)
```


```{r}
# VEH: Vehicles
df$VEH <- factor(df$VEH, ordered = TRUE, levels = c(0,1,2,3,4,5,6), 
                 labels = c(1,2,3,4,5,6,7))

barplot(summary(df$VEH), main = 'VEH: Vehicles')
```

```{r}
# MV: When move into house
df$MV <- factor(df$MV, ordered = TRUE, levels = c(1,2,3,4,5,6,7))

barplot(summary(df$MV), main = 'MV: When move into house')
```


```{r}
# NP: Number of persons in this household
# Merge 7-20
df$NP[df$NP>=7] <- 7
df$NP <- factor(df$NP, ordered = TRUE, levels = 1:7)

barplot(summary(df$NP), main = 'NP: Number of persons in this household')

```


```{r}
# RMSP: Number of rooms
# 1-19 maximum
df$RMSP <- factor(df$RMSP, ordered = TRUE, levels = min(df$RMSP):max(df$RMSP))

barplot(summary(df$RMSP), main = 'RMSP: Number of rooms')
```


```{r}
# ENG: Ability to speak english 
# Turn NA into one separate group: Excellent
df$ENG[is.na(df$ENG)] <- 0
# reorder
df$ENG <- 5 - df$ENG
df$ENG <- factor(df$ENG, ordered = TRUE, levels = 1:5)

barplot(summary(df$ENG ), main = 'NG: Ability to speak english')
```

```{r}
# MARHT: Number of times married - start at 1
df$MARHT[is.na(df$MARHT)] <- 0
df$MARHT <- factor(df$MARHT, ordered = TRUE, levels = c(0,1,2,3),
                   labels = c(1,2,3,4))

barplot(summary(df$MARHT ), main = 'MARHT: Number of times married')
```

```{r}
# SCHL: Educational attainment
# Group together no diploma group
df$SCHL[df$SCHL <=15 & df$SCHL>=2]  <- 2
# Group together high school group
df$SCHL[df$SCHL <=19 & df$SCHL>=16]  <- 3
# Group together master degree group
df$SCHL[df$SCHL <=23 & df$SCHL>=22]  <- 22
df$SCHL <- factor(df$SCHL, ordered = TRUE, levels = c(1,2,3,20,21,22,24),
                  labels = c(1,2,3,4,5,6,7))

barplot(summary(df$SCHL), main = 'SCHL: Educational attainment')
```


```{r}
# RACNUM: Number of major race groups represented
# Combine level 2 to 6
df$RACNUM[df$RACNUM>=2] <- 2
df$RACNUM <- factor(df$RACNUM, ordered = TRUE, levels = 1:2)

barplot(summary(df$RACNUM), main = 'RACNUM: Number of major race groups represented')
```

```{r}
# AGEP: Age
hist(df$AGEP, breaks = 30)
# Bin age by 5 years
df$AGEP <- cut(df$AGEP, seq(15,100,5), 
                 right=FALSE,
                 labels = 1:17)
df$AGEP <- factor(df$AGEP, ordered = TRUE, levels = 1:17)

barplot(summary(df$AGEP ), main = 'AGEP: Age')
```

```{r}
# WKL: When last worked

# group N/A as class 3 (never worked)
df$WKL[is.na(df$WKL)] <- 3
# reorder
df$WKL <- 4 - df$WKL
df$WKL <- factor(df$WKL, ordered = TRUE, levels = 1:3)

barplot(summary(df$WKL), main = 'WKL: When last worked')
```

```{r}
# PINCP: Total person's income
hist(df$PINCP , breaks = 30)
# reassign labels (the minimum is over -19998), binusing 20k range
df$PINCP[df$PINCP > 0 & df$PINCP <= 20000] <- 3
df$PINCP[df$PINCP > 20000 & df$PINCP <= 40000] <- 4
df$PINCP[df$PINCP > 40000 & df$PINCP <= 60000] <- 5
df$PINCP[df$PINCP > 60000 & df$PINCP <= 80000] <- 6
df$PINCP[df$PINCP > 80000 & df$PINCP <= 100000] <- 7
df$PINCP[df$PINCP > 100000 & df$PINCP <= 120000] <- 8
df$PINCP[df$PINCP > 120000 & df$PINCP <= 140000] <- 9
df$PINCP[df$PINCP > 140000 & df$PINCP <= 160000] <- 10
df$PINCP[df$PINCP > 160000 & df$PINCP <= 180000] <- 11
df$PINCP[df$PINCP > 180000 & df$PINCP <= 200000] <- 12
df$PINCP[df$PINCP > 200000] <- 13
df$PINCP[df$PINCP == 0] <- 2
df$PINCP[df$PINCP < 0] <- 1

df$PINCP <- factor(df$PINCP, ordered = TRUE, levels = 1:13)

barplot(summary(df$PINCP), main = 'PINCP: Total person income')

```

* * *



