
---
title: "MCAR 30%"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
```

* * *
```{r}
# sample MCAR dataset from PUMS, Make SCHL fully observed and MARHT missing
n = 10000
missing_prob = 0.3
set.seed(0)

# load dataset: df
load('../../Datasets/ordinalPUMS.Rdata')

# columns to be made MCAR
missing_col = c(1,3,6,9,10,11)

# sample n rows from the full dataset
sample <- sample(nrow(df), size = n)
df <- df[sample,]

# create MCAR scneario with missing_prob chance of missing: df_observed
df_observed <- df
for (col in missing_col) {
  missing_ind <- rbernoulli(n, p = missing_prob)
  df_observed[missing_ind, col] <- NA
}
```

```{r}
# save the file as .csv
write.table(df_observed,"./MCAR_30percent_woSCHL.csv", row.names = FALSE, sep = ',')
write.table(df,"./PUMS_MCAR_30percent_woSCHL.csv", row.names = FALSE, sep = ',')
```

* * *



