
---
title: "MCAR 30% missing - Generative Adversarial Imputation Nets (GAIN)"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(mnormt)
library(coda)
```

* * *
```{r}
# sample MCAR dataset from PUMS
source("../../utils/sampleMCAR.R")
n = 10000
missing_col = c(1,3,7,9,10,11)
missing_prob = 0.3
set.seed(0)

output_list <- sampleMCAR(n, missing_prob)
df <- output_list[['df']]
df_observed <- output_list[['df_observed']]
```


### Generative Adversarial Imputation Nets (GAIN)

reference: https://arxiv.org/abs/1806.02920

```{r}
# Load imputed dataset
d1 = read.csv('../../GAIN/imputed_dataset/MCAR_30percent_1.csv', header = FALSE, sep = ',')
d2 = read.csv('../../GAIN/imputed_dataset/MCAR_30percent_2.csv', header = FALSE, sep = ',')
d3 = read.csv('../../GAIN/imputed_dataset/MCAR_30percent_3.csv', header = FALSE, sep = ',')
d4 = read.csv('../../GAIN/imputed_dataset/MCAR_30percent_4.csv', header = FALSE, sep = ',')
d5 = read.csv('../../GAIN/imputed_dataset/MCAR_30percent_5.csv', header = FALSE, sep = ',')
colnames(d1) = colnames(df)
colnames(d2) = colnames(df)
colnames(d3) = colnames(df)
colnames(d4) = colnames(df)
colnames(d5) = colnames(df)
imputed_df = rbind(d1, d2, d3, d4, d5)
```

Diagnostics

```{r, echo = FALSE}
for (var_index in missing_col) {
  y_original = df[,var_index]
  original_pmf = table(y_original)/length(y_original)
  
  # Observed distribution
  missing_indicator = is.na(df_observed)[,var_index]
  y_observed = y_original[!missing_indicator]
  observed_pmf = table(y_observed)/length(y_observed)
  
  # Extract variable from imputed data
  imputed_pmf = table(imputed_df[, var_index])/length(imputed_df[, var_index])
  
  results = rbind(original_pmf,observed_pmf,imputed_pmf)
  colnames(results)<- 1:dim(imputed_pmf)
  barplot(results, xlab = 'Category', beside = TRUE, 
          legend = TRUE, 
          main = paste('MICE:', colnames(df)[var_index]))
}
```

Assess bivariate joint distribution
```{r, echo = FALSE}
combinations = combn(1:11, 2)
original_dist = c()
imputed_dist = c()
levels = c(7,7,7,19,5,4,7,2,17,3,13)

for (i in 1:(dim(combinations)[2])) {
  variables = combinations[, i]
  # Compute the joint pmf in the original dataframe without missing values
  original_pmf = table(df[,variables])
  original_pmf = original_pmf/sum(original_pmf)
      
  # Compute the joint pmf in the imputed dataset and average over imputations
  imputed_pmf = table(factor(imputed_df[,variables[1]], 
                                levels = 1:(levels[variables[1]])),
                      factor(imputed_df[,variables[2]] ,
                                levels = 1:(levels[variables[2]])))
  imputed_pmf = imputed_pmf/sum(imputed_pmf)
  
  original_dist = rbind(original_dist, matrix(original_pmf, ncol = 1))
  imputed_dist = rbind(imputed_dist, matrix(imputed_pmf, ncol = 1))
}

plot(original_dist, imputed_dist, 
     xlab = 'Original joint pmf', ylab = 'Imputed joint pmf', 
     main = 'Bivariate pmf', ylim = c(0,0.5), xlim = c(0,0.5))
abline(0,1, col = 'gray')
abline(0,1.1, col = 'red')
abline(0, 0.9, col = 'red')
```

Assess bivariate joint distribution
```{r, echo = FALSE}
combinations = combn(1:11, 3)
original_dist = c()
imputed_dist = c()
levels = c(7,7,7,19,5,4,7,2,17,3,13)

for (i in 1:(dim(combinations)[2])) {
  variables = combinations[, i]
  # Compute the joint pmf in the original dataframe without missing values
  original_pmf = table(df[,variables])
  original_pmf = original_pmf/sum(original_pmf)
      
  # Compute the joint pmf in the imputed dataset and average over imputations
  imputed_pmf = table(factor(imputed_df[,variables[1]], 
                                levels = 1:(levels[variables[1]])),
                      factor(imputed_df[,variables[2]],
                                levels = 1:(levels[variables[2]])),
                      factor(imputed_df[,variables[3]],
                                levels = 1:(levels[variables[3]])))
  imputed_pmf = imputed_pmf/sum(imputed_pmf)
  
  original_dist = rbind(original_dist, matrix(original_pmf, ncol = 1))
  imputed_dist = rbind(imputed_dist, matrix(imputed_pmf, ncol = 1))
}

plot(original_dist, imputed_dist, 
     xlab = 'Original joint pmf', ylab = 'Imputed joint pmf', 
     main = 'Trivariate pmf', ylim = c(0,0.5), xlim = c(0,0.5))
abline(0,1, col = 'gray')
abline(0,1.1, col = 'red')
abline(0, 0.9, col = 'red')
```

```{r}
# calculate rmse
numeric_df = sapply(df, as.numeric)
normalized_df = t(t(numeric_df-1)/(apply(numeric_df, MARGIN = 2, FUN = max)-1))
numeric_impute = sapply(d1, as.numeric)
normalized_impute = t(t(numeric_impute-1)/(apply(numeric_df, MARGIN = 2, FUN = max)-1))

missing_matrix = is.na(df_observed)

rmse = sqrt(sum((normalized_df[missing_matrix] - normalized_impute[missing_matrix])^2)/sum(missing_matrix))
rmse
```

```{r, echo = FALSE, include = FALSE}
for (var_index in missing_col) {
  y_original = df[,var_index]
  original_pmf = table(y_original)
  
  # Observed distribution
  missing_indicator = is.na(df_observed)[,var_index]
  y_observed = y_original[!missing_indicator]
  observed_pmf = table(y_observed)
  
  # Extract variable from imputed data
  imputed_pmf = table(imputed_df[, var_index])/5
  
  results = rbind(original_pmf,observed_pmf,imputed_pmf)
  colnames(results)<- 1:dim(imputed_pmf)
  barplot(results, xlab = 'Category', beside = TRUE, 
          legend = TRUE, 
          main = paste('MICE:', colnames(df)[var_index]))
}
```
* * *



