
---
title: "Bias comparison of different models: MAR_30"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(readr)
library(xtable)
```

* * *

```{r}
source("../../utils/compute_bias.R")
data_name = 'MAR_30'
n_imputations = 50
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 1
bias = bias_models(data_name, n_way)
df = format_list(bias)
df_1way = df
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of bias for different imputation methods for data with 30% values MAR (Marginal probabilities)', digits = 3)
```

```{r, fig.width=5, fig.height = 2.5}
# boxplot for estimates for marginal distribution
setEPS()
postscript("../figures/bias_MAR_30.eps", width=9, height=5.5, horizontal = FALSE, onefile=FALSE)
par(cex.axis = 0.9)
boxplot(df[, c(1,2,3,4,7,8)], col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Bias', ylim = c(-0.01, 0.01))
dev.off()
```


```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 2
bias = bias_models(data_name, n_way)
df = format_list(bias)
df_2way = df
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of bias for different imputation methods for data with 30% values MAR (Bivariate probabilities)', digits = 3)
```


```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 3
bias = bias_models(data_name, n_way)
df = format_list(bias)
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of bias for different imputation methods for data with 30% values MAR (Trivariate probabilities)', digits = 3)
```

* * *



