
---
title: "Bias comparison of different models: MAR_45"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(readr)
```

* * *

```{r}
source("../../utils/compute_bias.R")
data_name = 'MAR_45'
n_imputations = 10
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 1
bias = bias_models(data_name, n_way)
df = format_list(bias)
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Bias', ylim = c(-0.05, 0.05),
        main = 'Bias from different imputation methods: Univariate pmf')
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 2
bias = bias_models(data_name, n_way)
df = format_list(bias)
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Bias', ylim = c(-0.0025, 0.0025),
        main = 'Bias from different imputation methods: Bivariate pmf')
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 3
bias = bias_models(data_name, n_way)
df = format_list(bias)
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Bias', ylim = c(-0.001, 0.001),
        main = 'Bias from different imputation methods: Trivariate pmf')
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 4
bias = bias_models(data_name, n_way)
df = format_list(bias)
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Bias', ylim = c(-0.001, 0.001),
        main = 'Bias from different imputation methods: Quadvariate pmf')
```
* * *



