
---
title: "Coverage comparison of different models: MCAR_45"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(readr)
library(xtable)
```

* * *

```{r}
source("../../utils/compute_coverage.R")
data_name = 'MCAR_45'
n_imputations = 50
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 1
coverage = coverage_models(data_name, n_way, n_imputations)
df = format_list(coverage)
df_1way = df
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of coverage for different imputation methods for data with 45% values MCAR (Marginal probabilities)', digits = 2)
```

```{r, fig.width=5, fig.height = 3}
# boxplot for estimates for marginal distribution
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Coverage (fraction)', ylim = c(0,1), 
        main = paste('Coverage from different imputation methods: Marginal pmf'))
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 2
coverage = coverage_models(data_name, n_way, n_imputations)
df = format_list(coverage)
df_2way = df
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of coverage for different imputation methods for data with 45% values MCAR (Bivariate probabilities)', digits = 2)
```

```{r, fig.width=5, fig.height = 3}
setEPS()
postscript("../figures/coverage_12way_MCAR_45.eps", width=11, height=6, horizontal = FALSE, onefile=FALSE)
par(mfrow=c(1,2), oma = c(5.5,4.5,0.2,0.2) + 0.1, mar = c(0.75,0.25,1.25,1.25) + 0.1)
boxplot(df_1way, col = 'light blue', ylim = c(0,1), main = paste('Marginal'),
        las = 2)
boxplot(df_2way, col = 'peachpuff', ylim = c(0,1), main = paste('Bivariate'), 
        las = 2, yaxt="n")
axis(2, labels=FALSE)
title(ylab = "Coverage (fraction)",
      outer = TRUE, line = 3)
dev.off()
```


```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 3
coverage = coverage_models(data_name, n_way, n_imputations)
df = format_list(coverage)
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of coverage for different imputation methods for data with 45% values MCAR (Trivariate probabilities)', digits = 2)
```

* * *



