
---
title: "Coverage comparison of different missing data mechanism: MAR, MCAR"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(readr)
library(xtable)
```

* * *

```{r}
source("../../utils/compute_coverage.R")
n_imputations = 10
n_way = 1
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
data_name = 'MAR_30'
coverage_MAR = coverage_models(data_name, n_way, n_imputations)
df_MAR = format_list(coverage_MAR)
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
data_name = 'MCAR_30'
coverage_MCAR = coverage_models(data_name, n_way, n_imputations)
df_MCAR = format_list(coverage_MCAR)
```

```{r}
get_missing_pmf <- function(data_name, n_way){
  # Calculate observed pmf from all 100 fully observed datasets
  # n_way: the number of way in joint distribution to be consider

  # return: OBSERVED_Q
  # OBSERVED_Q: array of observed joinf pmf of specified number of way of variables with missing values
  source("../../utils/load_data.R")
  MISSING_Q = c()
  
  filename_root = paste(data_name,'/',data_name,'_',sep ='')
  missing_col = c(1,3,7,9,10,11)
  combinations = combn(1:11, n_way)
  for (id in 1:100) {
    # load fully observed data
    filename = paste(filename_root, id, sep = '')
    print(filename)
    observed_df = load_data(filename)
    observed_pmf = c()
    for (i in 1:(dim(combinations)[2])) {
      variables = combinations[, i]
      if (any(missing_col %in% variables)) {
        # compute observed pmf
        observed_cont_table = c(table(observed_df[, variables]))
        observed_cont_table = observed_cont_table/sum(observed_cont_table)
        observed_pmf = c(observed_pmf, observed_cont_table)
      }
    }
    # store it into rows of OBSERVED_Q
    MISSING_Q = rbind(MISSING_Q, observed_pmf)
  }
  print('>> finish computing observed pmf from fully observed data')
  return(MISSING_Q)
}
```

```{r}
MISS_Q = get_missing_pmf(data_name, n_way)
MISS_Q = apply(MISS_Q, MARGIN = 2, mean)
```

```{r}
TRUE_Q = get_true_pmf(n_way)
```

```{r}
plot(MISS_Q,df_MCAR[,'MI-ord'], col = 'blue', ylab = 'coverage', ylim = c(0,1), main = 'MCAR')
points(MISS_Q, df_MCAR[,'MI-nom'],  col = 'red')
```


```{r}
plot(MISS_Q,df_MAR[,'MI-ord'], col = 'blue', ylab = 'coverage', ylim = c(0,1), main = 'MAR')
points(MISS_Q, df_MAR[,'MI-nom'],  col = 'red')
```

```{r}
plot(MISS_Q,df_MAR[,'MI-ord'] - df_MAR[,'MI-nom'], col = 'red', 
     ylab = 'difference in coverage', 
     ylim = c(0,1), main = 'MAR')
#points(MISS_Q, df_MAR[,'MI-ord'],  col = 'blue')
```
* * *



