
---
title: "MCAR 30% missing - MICE"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
library(mice)
```

* * *
```{r}
# sample MCAR dataset from PUMS
source("../../utils/sample_PUMS.R")
source("../../utils/make_MCAR.R")
n = 10000
missing_col = c(1,3,7,9,10,11)
missing_prob = 0.3
set.seed(0)

df <- sample_PUMS(n)
df_observed <- make_MCAR(df, missing_prob)
apply(is.na(df_observed), MARGIN = 2, mean)
```


### MICE

```{r}
n_imputations = 5
levels = c(7,7,7,19,5,4,7,2,17,3,13)

# format to be nominal variables
df_temp = df_observed
for (col_index in 1:ncol(df_temp)) {
  df_temp[,col_index] = factor(df_temp[,col_index], levels = 1:levels[col_index], ordered = FALSE)
}
print(class(df_temp[,1]))
# perform MICE imputation
imputed_df <-  mice(df_temp,m=n_imputations)

# collect results into list
imputation_list = list()
for (i in 1:n_imputations) {
  d = complete(imputed_df, i)
  # format columns of d to be ordinal variables
  for (col_index in 1:ncol(df_observed)) {
    d[,col_index] = factor(d[,col_index], levels = 1:levels[col_index], ordered = TRUE)
  }
  imputation_list[[i]] = d
}
print(class(imputation_list[[1]][,1]))
```



Diagnostics

```{r}
imputed_df$loggedEvents$meth
```




* * *



