
---
title: "Relative MSE comparison of different models: MAR_45"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(readr)
library(xtable)
```

* * *

```{r}
source("../../utils/compute_rel_MSE.R")
data_name = 'MAR_45'
n_imputations = 50
```


```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 1
rel_MSE = rel_MSE_models(data_name, n_way)
df = format_list(rel_MSE)
df_1way = df
```

```{r}
summary = apply(df[,c(1,2,3,4,7,8)], MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of relative MSE for different imputation methods for data with 45% values MAR (Marginal probabilities)', digits = 2)
```


```{r, fig.width=5, fig.height = 3}
boxplot(df, col = 'light blue', xlab = 'Imputation method', 
        ylab = 'Relative MSE (fraction)', ylim = c(0,500), 
        main = paste('Relative MSE from different imputation methods: Marginal pmf'))
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 2
rel_MSE = rel_MSE_models(data_name, n_way)
df = format_list(rel_MSE)
df_2way = df
```


```{r}
summary = apply(df[,c(1,2,3,4,7,8)], MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of relative MSE for different imputation methods for data with 45% values MAR (Bivariate probabilities)', digits = 2)
```

```{r, fig.width=5, fig.height = 3}
setEPS()
postscript("../figures/rmse_12way_MAR_45.eps", width=10, height=6, horizontal = FALSE, onefile=FALSE)
par(mfrow=c(1,2), oma = c(5.5,4.5,0.2,0.2) + 0.1, mar = c(0.75,0.25,1.25,1.25) + 0.1)
boxplot(df_1way[, c(1,2,3,4,7,8)], col = 'light blue', ylim = c(0,30), main = paste('Marginal'),
        las = 2)
boxplot(df_2way[,c(1,2,3,4,7,8)], col = 'peachpuff', ylim = c(0,30), main = paste('Bivariate'), 
        las = 2, yaxt="n")
axis(2, labels=FALSE)
title(ylab = "Relative MSE (fraction)",
      outer = TRUE, line = 3)
dev.off()
```

```{r, results="hide", warning = FALSE, message=FALSE, echo = FALSE}
n_way = 3
rel_MSE = rel_MSE_models(data_name, n_way)
df = format_list(rel_MSE)
```

```{r}
summary = apply(df, MARGIN = 2, quantile , probs = c(0, 0.25, 0.5, 0.75, 1))
rownames(summary) <- c('Min.', '1st Qu.', 'Median', '3rd Qu.', 'Max.')
xtable(summary, caption = 'Distribution of relative MSE for different imputation methods for data with 45% values MAR (Trivariate probabilities)', digits = 2)
```

* * *



