
---
title: "MCAR 30% missing - MICE-CART"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
library(mice)
```

* * *

```{r}
# Root for different dataset
root_fully_observed <- 'fully_observed/fully_observed_'
root_MCAR_30 <- 'MCAR_30/MCAR_30_'
root_MCAR_45 <- 'MCAR_45/MCAR_45_'
root_MAR_30 <- 'MAR_30/MAR_30_'
root_MAR_45 <- 'MAR_45/MAR_45_'
source('../../utils/load_data.R')
miss_df = c()
miss_MCAR_30 = c()
miss_MCAR_45 = c()
miss_MAR_30 = c()
miss_MAR_45 = c()

for (i in 1:100) {
  # Obtain a full path for the file to be saved
  name_fully_observed <- paste(root_fully_observed, i, sep = '')
  name_MCAR_30 <- paste(root_MCAR_30, i, sep = '')
  name_MCAR_45 <- paste(root_MCAR_45, i, sep = '')
  name_MAR_30 <- paste(root_MAR_30, i, sep = '')
  name_MAR_45 <- paste(root_MAR_45, i, sep = '')
  
  # load data
  df = load_data(name_fully_observed)
  MCAR_30 <- load_data(name_MCAR_30)
  MCAR_45 <- load_data(name_MCAR_45)
  MAR_30 <- load_data(name_MAR_30)
  MAR_45 <- load_data(name_MAR_45)
  
  # compute missing probability
  miss_df = rbind(miss_df, apply(is.na(df), MARGIN = 2, mean))
  miss_MCAR_30 = rbind(miss_MCAR_30, apply(is.na(MCAR_30), MARGIN = 2, mean))
  miss_MCAR_45 = rbind(miss_MCAR_45, apply(is.na(MCAR_45), MARGIN = 2, mean))
  miss_MAR_30 = rbind(miss_MAR_30, apply(is.na(MAR_30), MARGIN = 2, mean))
  miss_MAR_45 = rbind(miss_MAR_45,apply(is.na(MAR_45), MARGIN = 2, mean))
  print(paste('>> finish computing:',i))
}
```

```{r}
# minimum
apply(miss_df, MARGIN = 2, min)
apply(miss_MCAR_30, MARGIN = 2, min)
apply(miss_MCAR_45, MARGIN = 2, min)
apply(miss_MAR_30, MARGIN = 2, min)
apply(miss_MAR_45, MARGIN = 2, min)
```

```{r}
# maximum
apply(miss_df, MARGIN = 2, max)
apply(miss_MCAR_30, MARGIN = 2, max)
apply(miss_MCAR_45, MARGIN = 2, max)
apply(miss_MAR_30, MARGIN = 2, max)
apply(miss_MAR_45, MARGIN = 2, max)
```

```{r}
# mean
apply(miss_df, MARGIN = 2, mean)
apply(miss_MCAR_30, MARGIN = 2, mean)
apply(miss_MCAR_45, MARGIN = 2, mean)
apply(miss_MAR_30, MARGIN = 2, mean)
apply(miss_MAR_45, MARGIN = 2, mean)
```

```{r}
# overall mean
missing_col = c(1,3,7,9,10,11)
mean(miss_MCAR_30[,missing_col])
mean(miss_MCAR_45[,missing_col])
mean(miss_MAR_30[,missing_col])
mean(miss_MAR_45[,missing_col])
```

```{r}
# no missing value
boxplot(miss_df)
```

```{r}
boxplot(miss_MCAR_30)
boxplot(miss_MCAR_45)
boxplot(miss_MAR_30)
boxplot(miss_MAR_45)
```


```{r}
i = 1
# Obtain a full path for the file to be saved
name_fully_observed <- paste(root_fully_observed, i, sep = '')
name_MCAR_30 <- paste(root_MCAR_30, i, sep = '')
name_MCAR_45 <- paste(root_MCAR_45, i, sep = '')
name_MAR_30 <- paste(root_MAR_30, i, sep = '')
name_MAR_45 <- paste(root_MAR_45, i, sep = '')

# load data
df_1 = load_data(name_fully_observed)
MCAR_30_1 <- load_data(name_MCAR_30)
MCAR_45_1 <- load_data(name_MCAR_45)
MAR_30_1 <- load_data(name_MAR_30)
MAR_45_1 <- load_data(name_MAR_45)

i = 2
# Obtain a full path for the file to be saved
name_fully_observed <- paste(root_fully_observed, i, sep = '')
name_MCAR_30 <- paste(root_MCAR_30, i, sep = '')
name_MCAR_45 <- paste(root_MCAR_45, i, sep = '')
name_MAR_30 <- paste(root_MAR_30, i, sep = '')
name_MAR_45 <- paste(root_MAR_45, i, sep = '')

# load data
df_2 = load_data(name_fully_observed)
MCAR_30_2 <- load_data(name_MCAR_30)
MCAR_45_2 <- load_data(name_MCAR_45)
MAR_30_2 <- load_data(name_MAR_30)
MAR_45_2 <- load_data(name_MAR_45)
```

* * *



