
---
title: "Test function marginal_pmf_plot"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
```

* * *

```{r}
data_name = 'MAR_30'
```

```{r}
source("../../utils/load_result.R")
source("../../utils/get_true_pmf.R")
```

```{r}
models = c('MICE_NOM', 'MICE', 'CART', 'FOREST', 'GAIN', 'GAIN_CAT', 'DP', 'PROBIT')
report_name = c('MI-nom', 'MI-ord', 'MI-cart', 'Forest', 'GAIN', 'GAINcat', 'DPMPM', 'DPMMVN')
# get true pmf
true_pmf = get_true_pmf(n_way=1)

par(mfrow=c(2,4), oma = c(5,4,0,0) + 0.1, mar = c(0.25,0.25,1.25,1.25) + 0.1, 
    cex.axis = 1.25, cex.lab=1.25)
for (i in 1:length(models)) {
  # for each model, get marginal pmf
  model_name = models[i]
  output_list = load_result(model_name, data_name, n_way=1)
  q_bar = output_list[['q_bar']] # mean estimate
  
  # calculate imputed pmf
  imputed_pmf = apply(q_bar, MARGIN = 2, mean)
  title = report_name[i]
  if (i==1) {
    # top left
    plot(imputed_pmf, true_pmf, main = title, xlim =c(0,0.7), ylim = c(0,0.7), xaxt="n")
    axis(1, labels=FALSE)
  }else if(i %in% c(2,3,4)){
    # top row
    plot(imputed_pmf, true_pmf, main = title, xlim =c(0,0.7), ylim = c(0,0.7), xaxt="n",
         yaxt="n")
    axis(1, labels=FALSE)
    axis(2, labels=FALSE)
  }else if(i == 5){
    # bottom left
    plot(imputed_pmf, true_pmf, main = title, xlim =c(0,0.7), ylim = c(0,0.7))
  }else{
    # bottom rows
    plot(imputed_pmf, true_pmf, main = title, xlim =c(0,0.7), ylim = c(0,0.7),
         yaxt="n")
    axis(2, labels=FALSE)
  }
  abline(0,1, col = 'gray')
  abline(0,1.1, col = 'red')
  abline(0, 0.9, col = 'red')
}

title(xlab = "Average imputed marginal pmf",
      ylab = "Population marginal pmf",
      outer = TRUE, line = 3)

```



```{r}

models = c('MICE_NOM')
report_name = c('MI-nom')
# get true pmf
true_pmf = get_true_pmf(n_way=1)

par(mfrow=c(2,4))
for (i in 1:length(models)) {
  # for each model, get marginal pmf
  model_name = models[i]
  output_list = load_result(model_name, data_name, n_way=1)
  q_bar = output_list[['q_bar']] # mean estimate
  
  # calculate imputed pmf
  imputed_pmf = apply(q_bar, MARGIN = 2, mean)
  title = paste('Assess imputed pmf:', report_name[i])
  plot(imputed_pmf, true_pmf, 
         xlab = 'Average imputed univariate pmf', ylab = 'Population univariate pmf', 
         main = title)
  abline(0,1, col = 'gray')
  abline(0,1.1, col = 'red')
  abline(0, 0.9, col = 'red')
}

```

* * *



