
---
title: "MCAR 30% missing - MICE-CART"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
```

* * *
```{r}
# sample MCAR dataset from PUMS
source("../../utils/sampleMCAR.R")
n = 10000
missing_col = c(1,3,7,9,10,11)
missing_prob = 0.3
set.seed(0)

output_list <- sampleMCAR(n, missing_prob)
df <- output_list[['df']]
df_observed <- output_list[['df_observed']]
```

### MICE-CART
Create 5 imputed dataset
```{r}
library(mice)
imputed_df <-  mice(df_observed,m=5,method="cart",print=F)
```

Extract the 5 imputed dataset

```{r}
imputation_list = list()
for (i in 1:5) {
  imputation_list[[i]] = complete(imputed_df, i)
}
```

Diagnostics
```{r}
# Identify possible combinations
n_way = 2
load('../../Datasets/ordinalPUMS.Rdata')
combinations = combn(1:11, n_way)
true_cont_table = c()
for (i in 1:(dim(combinations)[2])) {
  variables = combinations[, i]
  if (any(missing_col %in% variables)) {
    # Calculate true contingency probability
    dummy = c(table(df[, variables]))
    dummy = dummy/sum(dummy)
    true_cont_table = c(true_cont_table, dummy)
  }
}
```

```{r}
source("../../utils/calculate_statistics.R")
output_list = calculate_statistics(imputation_list, n_way=2, missing_col)
n_imputations = 5
dof = output_list[['dof']]
mean_estimate = output_list[['q_bar']]
within_group_var = output_list[['u_bar']]
across_group_var = output_list[['b']]
total_var = (1+1/n_imputations)*across_group_var + within_group_var
total_sd = sqrt(total_var)
# Calculate quantile for 95% confidence interval from t distribution
q_alpha = qt(0.975, df = dof)

# Calculate upper and lower bound of 95% confidence interval
upper_bound = mean_estimate+q_alpha*total_sd
lower_bound = mean_estimate-q_alpha*total_sd

# should receive output of 96.16 percent
coverage = c(lower_bound<=true_cont_table & true_cont_table<=upper_bound)
mean(coverage[!is.na(coverage)])
```

* * *



