
---
title: "MCAR 30% missing - DPMPM"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
library(tigerstats)
library(leaps)
library(car)
library(rms)
require(caret)
require(e1071)
library(lme4) 
library(lattice)
library(broom)
library(boot)
library(ggplot2)
library(cobalt)
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(MCMCpack)
library(abind)
library(matrixStats)
library(truncnorm)
library(mvtnorm)
library(MCMCpack)
library(mnormt)
library(coda)
library(NPBayesImputeCat)
```

* * *
```{r}
# sample MCAR dataset from PUMS
source("../../utils/sampleMCAR.R")
n = 10000
missing_col = c(1,3,7,9,10,11)
missing_prob = 0.3
set.seed(0)

output_list <- sampleMCAR(n, missing_prob)
df <- output_list[['df']]
df_observed <- output_list[['df_observed']]
```


### DPMPM

```{r}
source('../../utils/models/DP_imputation.R')
imputation_list = DP_imputation(df_observed, 5)
```

```{r}
# Unpack imputation_list
d1 = imputation_list[[1]]
d2 = imputation_list[[2]]
d3 = imputation_list[[3]]
d4 = imputation_list[[4]]
d5 = imputation_list[[5]]

n_observation = dim(d1)[1]
n_imputations = 5

# Prepare output format
q_bar = c() # mean estimate across five imputation sets
u_bar = c() # within group variance
b = c() # between group variance
dof = c() # degree of freedom

# Identify possible combinations
combinations = combn(1:11, 2)
```

```{r}
for (i in 1:1) {
    variables = c(3,4)
    if (any(missing_col %in% variables)) {
      # if one of the combination has missing values
      # Calculate contingency table respect to that combination
      cont_table_1 = c(table(d1[,variables]))
      cont_table_2 = c(table(d2[,variables]))
      cont_table_3 = c(table(d3[,variables]))
      cont_table_4 = c(table(d4[,variables]))
      cont_table_5 = c(table(d5[,variables]))
      print(cont_table_1)
      cont_table_2
      cont_table_3
      cont_table_4
      cont_table_5
      # Normalize contingency table
      cont_table_1 = cont_table_1/sum(cont_table_1)
      cont_table_2 = cont_table_2/sum(cont_table_2)
      cont_table_3 = cont_table_3/sum(cont_table_3)
      cont_table_4 = cont_table_4/sum(cont_table_4)
      cont_table_5 = cont_table_5/sum(cont_table_5)
      
      # Combind them into one table: n_imputationxn_combinations
      cont_table = rbind(cont_table_1, cont_table_2, cont_table_3, cont_table_4, cont_table_5)
      
      
    }
  }
```

```{r}
for (i in 1:(dim(combinations)[2])) {
    variables = combinations[, i]
    if (any(missing_col %in% variables)) {
      # if one of the combination has missing values
      # Calculate contingency table respect to that combination
      cont_table_1 = c(table(d1[,variables]))
      cont_table_2 = c(table(d2[,variables]))
      cont_table_3 = c(table(d3[,variables]))
      cont_table_4 = c(table(d4[,variables]))
      cont_table_5 = c(table(d5[,variables]))
      # Normalize contingency table
      cont_table_1 = cont_table_1/sum(cont_table_1)
      cont_table_2 = cont_table_2/sum(cont_table_2)
      cont_table_3 = cont_table_3/sum(cont_table_3)
      cont_table_4 = cont_table_4/sum(cont_table_4)
      cont_table_5 = cont_table_5/sum(cont_table_5)
      
      # Combind them into one table: n_imputationxn_combinations
      cont_table = rbind(cont_table_1, cont_table_2, cont_table_3, cont_table_4, cont_table_5)
      
      # Calculate MI estimate of P
      mean_estimate = apply(cont_table, MARGIN = 2, FUN = mean)
      q_bar = c(q_bar, mean_estimate)
      
      # Calculate within group variance: p(1-p)/n
      within_group_var = apply(cont_table*(1-cont_table)/n_observation, MARGIN = 2, FUN = mean)
      u_bar = c(u_bar, within_group_var)
      
      # Calculate across group variance: sum(p-p_bar)^2/(m-1)
      across_group_var = apply((t(t(cont_table) - mean_estimate))^2, MARGIN = 2, FUN = sum)/(n_imputations-1)
      b = c(b, across_group_var)
      
      # Calculate Rubin degree of freedom:dof
      rM = (1+1/n_imputations)*across_group_var/within_group_var
      dof = c(dof, (n_imputations-1)*(1+1/rM)^2)
      
    }
  }
```

* * *



